project_id = "drqbvxrouedaohmwfvdj"

[auth]
enabled = true
#site_url = "http://localhost:3000"

[functions.generate-story]
verify_jwt = false

[functions.ip-sanitizer]
verify_jwt = false

[functions.generate-characters]
verify_jwt = false

[functions.generate-phase1]
verify_jwt = false

[functions.generate-phase2]
verify_jwt = false

[functions.generate-phase3]
verify_jwt = false

[functions.generate-phase4]
verify_jwt = false

[functions.generate-phase5]
verify_jwt = false

[functions.generate-phase6]
verify_jwt = false

[functions.detect-intent]
verify_jwt = false