project_id = "drqbvxrouedaohmwfvdj"

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.generate-story]
verify_jwt = false

[functions.ip-sanitizer]
verify_jwt = false

[functions.generate-characters]
verify_jwt = false